create table if not exists public.patient_cases (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  patient_name text,
  age integer,
  symptoms text not null,
  category text not null,
  risk_level text not null,
  recommendation text not null,
  score integer not null,
  raw_data jsonb not null,
  review_status text not null default 'New',
  doctor_notes text not null default '',
  share_code text unique,
  patient_consent boolean not null default false
);

alter table public.patient_cases
add column if not exists review_status text not null default 'New';

alter table public.patient_cases
add column if not exists doctor_notes text not null default '';

alter table public.patient_cases
add column if not exists share_code text unique;

alter table public.patient_cases
add column if not exists patient_consent boolean not null default false;

alter table public.patient_cases enable row level security;

drop policy if exists "Allow app inserts for patient cases" on public.patient_cases;
drop policy if exists "Allow app reads for patient dashboard" on public.patient_cases;
drop policy if exists "Allow app reset for patient cases" on public.patient_cases;
drop policy if exists "Allow app review updates for patient cases" on public.patient_cases;
drop policy if exists "Allow authenticated staff reads" on public.patient_cases;
drop policy if exists "Allow authenticated staff deletes" on public.patient_cases;
drop policy if exists "Allow authenticated staff review updates" on public.patient_cases;

create policy "Allow app inserts for patient cases"
on public.patient_cases
for insert
to anon
with check (true);

create policy "Allow authenticated staff reads"
on public.patient_cases
for select
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'staff');

create policy "Allow authenticated staff deletes"
on public.patient_cases
for delete
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'staff');

create policy "Allow authenticated staff review updates"
on public.patient_cases
for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'staff')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'staff');

-- Patients may retrieve only the small response associated with a private,
-- unguessable case code. Anonymous users never receive table-wide SELECT.
create or replace function public.get_patient_case_by_share_code(input_code text)
returns table (
  created_at timestamptz,
  patient_name text,
  risk_level text,
  review_status text,
  doctor_notes text,
  share_code text
)
language sql
security definer
set search_path = public
as $$
  select p.created_at, p.patient_name, p.risk_level, p.review_status,
         p.doctor_notes, p.share_code
  from public.patient_cases p
  where p.share_code = upper(trim(input_code))
    and p.patient_consent = true
  limit 1;
$$;

revoke all on function public.get_patient_case_by_share_code(text) from public;
grant execute on function public.get_patient_case_by_share_code(text) to anon, authenticated;

create index if not exists patient_cases_score_idx
on public.patient_cases (score desc);

create index if not exists patient_cases_created_at_idx
on public.patient_cases (created_at desc);
