create table if not exists public.patient_cases (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  patient_name text,
  age integer,
  symptoms text not null,
  category text not null,
  risk_level text not null,
  recommendation text not null,
  score integer not null,
  raw_data jsonb not null,
  review_status text not null default 'New',
  doctor_notes text not null default '',
  share_code text unique,
  patient_consent boolean not null default false
);

alter table public.patient_cases
add column if not exists review_status text not null default 'New';

alter table public.patient_cases
add column if not exists doctor_notes text not null default '';

alter table public.patient_cases
add column if not exists share_code text unique;

alter table public.patient_cases
add column if not exists patient_consent boolean not null default false;

update public.patient_cases
set review_status = 'New'
where review_status is null
   or review_status not in ('New', 'Reviewed', 'Book appointment', 'Seek urgent care', 'Resolved');

update public.patient_cases
set doctor_notes = left(coalesce(doctor_notes, ''), 1200)
where doctor_notes is null
   or char_length(doctor_notes) > 1200;

update public.patient_cases
set patient_consent = false
where patient_consent is null;

alter table public.patient_cases
alter column review_status set default 'New',
alter column review_status set not null,
alter column doctor_notes set default '',
alter column doctor_notes set not null,
alter column patient_consent set default false,
alter column patient_consent set not null;

alter table public.patient_cases
drop constraint if exists patient_cases_review_status_check;

alter table public.patient_cases
add constraint patient_cases_review_status_check
check (review_status in ('New', 'Reviewed', 'Book appointment', 'Seek urgent care', 'Resolved'));

alter table public.patient_cases
drop constraint if exists patient_cases_doctor_notes_length_check;

alter table public.patient_cases
add constraint patient_cases_doctor_notes_length_check
check (char_length(doctor_notes) <= 1200);

alter table public.patient_cases enable row level security;

drop policy if exists "Allow app inserts for patient cases" on public.patient_cases;
drop policy if exists "Allow app reads for patient dashboard" on public.patient_cases;
drop policy if exists "Allow app reset for patient cases" on public.patient_cases;
drop policy if exists "Allow app review updates for patient cases" on public.patient_cases;
drop policy if exists "Allow authenticated staff reads" on public.patient_cases;
drop policy if exists "Allow authenticated staff deletes" on public.patient_cases;
drop policy if exists "Allow authenticated staff review updates" on public.patient_cases;

create policy "Allow app inserts for patient cases"
on public.patient_cases
for insert
to anon
with check (true);

create policy "Allow authenticated staff reads"
on public.patient_cases
for select
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'staff');

create policy "Allow authenticated staff deletes"
on public.patient_cases
for delete
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'staff');

create policy "Allow authenticated staff review updates"
on public.patient_cases
for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'staff')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'staff');

-- Patients may retrieve only the small response associated with a private,
-- unguessable case code. Anonymous users never receive table-wide SELECT.
create or replace function public.get_patient_case_by_share_code(input_code text)
returns table (
  created_at timestamptz,
  patient_name text,
  risk_level text,
  review_status text,
  doctor_notes text,
  share_code text
)
language sql
security definer
set search_path = public
as $$
  select p.created_at, p.patient_name, p.risk_level, p.review_status,
         p.doctor_notes, p.share_code
  from public.patient_cases p
  where p.share_code = case
      when upper(regexp_replace(coalesce(input_code, ''), '\s+', '', 'g')) like 'LL-%'
        then upper(regexp_replace(coalesce(input_code, ''), '\s+', '', 'g'))
      when upper(regexp_replace(coalesce(input_code, ''), '\s+', '', 'g')) like 'LL%'
        then 'LL-' || substring(upper(regexp_replace(coalesce(input_code, ''), '\s+', '', 'g')) from 3)
      else upper(regexp_replace(coalesce(input_code, ''), '\s+', '', 'g'))
    end
    and p.patient_consent = true
  limit 1;
$$;

revoke all on function public.get_patient_case_by_share_code(text) from public;
grant execute on function public.get_patient_case_by_share_code(text) to anon, authenticated;

create index if not exists patient_cases_score_idx
on public.patient_cases (score desc);

create index if not exists patient_cases_created_at_idx
on public.patient_cases (created_at desc);
