create table if not exists public.patient_cases (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  patient_name text,
  age integer,
  symptoms text not null,
  category text not null,
  risk_level text not null,
  recommendation text not null,
  score integer not null,
  raw_data jsonb not null,
  review_status text not null default 'New',
  doctor_notes text not null default '',
  share_code text unique,
  patient_consent boolean not null default false
);

alter table public.patient_cases
add column if not exists review_status text not null default 'New';

alter table public.patient_cases
add column if not exists doctor_notes text not null default '';

alter table public.patient_cases
add column if not exists share_code text unique;

alter table public.patient_cases
add column if not exists patient_consent boolean not null default false;

alter table public.patient_cases enable row level security;

create policy "Allow app inserts for patient cases"
on public.patient_cases
for insert
to anon
with check (true);

create policy "Allow app reads for patient dashboard"
on public.patient_cases
for select
to anon
using (true);

create policy "Allow app reset for patient cases"
on public.patient_cases
for delete
to anon
using (true);

create policy "Allow app review updates for patient cases"
on public.patient_cases
for update
to anon
using (true)
with check (true);

create index if not exists patient_cases_score_idx
on public.patient_cases (score desc);

create index if not exists patient_cases_created_at_idx
on public.patient_cases (created_at desc);
